//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HashChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// ██╗  ██╗ █████╗ ███████╗██╗  ██╗     ██████╗██╗  ██╗███████╗ ██████╗██╗  ██╗███████╗██████╗ 
        /// ██║  ██║██╔══██╗██╔════╝██║  ██║    ██╔════╝██║  ██║██╔════╝██╔════╝██║ ██╔╝██╔════╝██╔══██╗
        /// ███████║███████║███████╗███████║    ██║     ███████║█████╗  ██║     █████╔╝ █████╗  ██████╔╝
        /// ██╔══██║██╔══██║╚════██║██╔══██║    ██║     ██╔══██║██╔══╝  ██║     ██╔═██╗ ██╔══╝  ██╔══██╗
        /// ██║  ██║██║  ██║███████║██║  ██║    ╚██████╗██║  ██║███████╗╚██████╗██║  ██╗███████╗██║  ██║
        /// ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string banner {
            get {
                return ResourceManager.GetString("banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;scans&quot;:{
        ///      &quot;Bkav&quot;:{
        ///         &quot;detected&quot;:false,
        ///         &quot;version&quot;:&quot;1.3.0.9899&quot;,
        ///         &quot;result&quot;:null,
        ///         &quot;update&quot;:&quot;20190320&quot;
        ///      },
        ///      &quot;MicroWorld-eScan&quot;:{
        ///         &quot;detected&quot;:false,
        ///         &quot;version&quot;:&quot;14.0.297.0&quot;,
        ///         &quot;result&quot;:null,
        ///         &quot;update&quot;:&quot;20190321&quot;
        ///      },
        ///      &quot;CMC&quot;:{
        ///         &quot;detected&quot;:false,
        ///         &quot;version&quot;:&quot;1.1.0.977&quot;,
        ///         &quot;result&quot;:null,
        ///         &quot;update&quot;:&quot;20190321&quot;
        ///      },
        ///      &quot;CAT-QuickHeal&quot;:{
        ///         &quot;detected&quot;:false,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scanMD5result {
            get {
                return ResourceManager.GetString("scanMD5result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;proxyAdress&quot;: &quot;http://mcafeewgf5.int.teb.com.tr:80&quot;,
        ///  &quot;proxyUsername&quot;: &quot;P31908&quot;,
        ///  &quot;proxyPassword&quot;: &quot;nononononono&quot;,
        ///  &quot;csirtMail&quot;: &quot;siberolay@teb.com.tr&quot;,
        ///  &quot;ksdestekMail&quot;: &quot;kullaniciservisleridestek@teb.com.tr&quot;,
        ///  &quot;atarMail&quot;: &quot;AtarMail@teb.com.tr&quot;,
        ///  &quot;atarTitle&quot;: &quot;ATAR_TEB_INT_&quot;,
        ///  &quot;vtApiKeys&quot;: [
        ///    {&quot;id&quot;: &quot;k1&quot;,&quot;pass&quot;: &quot;4b17dea20e1caa790f045dcb5b3063a15428f8fe4a00d907fa5e9d70f8dee258&quot;},
        ///    {&quot;id&quot;: &quot;k2&quot;,&quot;pass&quot;: &quot;bb4f6a9193534b8e053bc19a717ec3023aaba49e2a2089ee2c9a6b74a658b161&quot;},
        ///    {&quot;id&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string speconfig {
            get {
                return ResourceManager.GetString("speconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon vicon {
            get {
                object obj = ResourceManager.GetObject("vicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
