//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HashChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	███╗   ███╗██████╗ ███████╗     ██████╗██╗  ██╗███████╗ ██████╗██╗  ██╗███████╗██████╗ 
        ///	████╗ ████║██╔══██╗██╔════╝    ██╔════╝██║  ██║██╔════╝██╔════╝██║ ██╔╝██╔════╝██╔══██╗
        ///	██╔████╔██║██║  ██║███████╗    ██║     ███████║█████╗  ██║     █████╔╝ █████╗  ██████╔╝
        ///	██║╚██╔╝██║██║  ██║╚════██║    ██║     ██╔══██║██╔══╝  ██║     ██╔═██╗ ██╔══╝  ██╔══██╗
        ///	██║ ╚═╝ ██║██████╔╝███████║    ╚██████╗██║  ██║███████╗╚██████╗██║  ██╗███████╗██║  ██║
        ///	╚═╝     ╚═╝╚═════╝ ╚══════╝     ╚═════╝╚═╝  ╚═╝╚══════╝ ╚══ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string banner {
            get {
                return ResourceManager.GetString("banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;scans&quot;:{
        ///      &quot;Bkav&quot;:{
        ///         &quot;detected&quot;:false,
        ///         &quot;version&quot;:&quot;1.3.0.9899&quot;,
        ///         &quot;result&quot;:null,
        ///         &quot;update&quot;:&quot;20190320&quot;
        ///      },
        ///      &quot;MicroWorld-eScan&quot;:{
        ///         &quot;detected&quot;:false,
        ///         &quot;version&quot;:&quot;14.0.297.0&quot;,
        ///         &quot;result&quot;:null,
        ///         &quot;update&quot;:&quot;20190321&quot;
        ///      },
        ///      &quot;CMC&quot;:{
        ///         &quot;detected&quot;:false,
        ///         &quot;version&quot;:&quot;1.1.0.977&quot;,
        ///         &quot;result&quot;:null,
        ///         &quot;update&quot;:&quot;20190321&quot;
        ///      },
        ///      &quot;CAT-QuickHeal&quot;:{
        ///         &quot;detected&quot;:false,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scanMD5result {
            get {
                return ResourceManager.GetString("scanMD5result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon vicon {
            get {
                object obj = ResourceManager.GetObject("vicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
